version: '3.8'

services:
  knowme-profile-app:
    image:  knowme-profile:005
    ports:
      - "8062:8062"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://profiledb:5432/profile
      SPRING_DATASOURCE_USERNAME: profile1
      SPRING_DATASOURCE_PASSWORD: profile2
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_SHOW_SQL: 'true'
      SPRING_JPA_HIBERNATE_DDL_AUTO: create
    depends_on:
      - postgres

  postgres:
    image: postgres:latest
    container_name: profiledb
    environment:
      POSTGRES_DB: profile2
      POSTGRES_USER: 'profile1'
      POSTGRES_PASSWORD: 'profile2'
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: