version: '3.8'

services:
  knowme-profile:
    image: knowme-profile:latest
    restart: always
    ports:
      - "8062:8062"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-profile:5432/profile
      SPRING_DATASOURCE_USERNAME: "postgres"
      SPRING_DATASOURCE_PASSWORD: "postgres123"
      SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT: org.hibernate.dialect.PostgreSQLDialect
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_JPA_SHOW_SQL: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: update
    depends_on:
      - postgres-profile
  postgres-profile:
    image: postgres:latest
    restart: always
    container_name: postgres-profile-co
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres123"
      POSTGRES_DB: "profile"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/docker/volumes

volumes:
  postgres_data:
